env:
   global:
     - CONAN_USE_DOCKER=1
linux: &linux
   os: linux
   dist: xenial
   language: python
   python: "3.7"
   services:
     - docker
matrix:
   include:
      - <<: *linux
        env: CONAN_GCC_VERSIONS=4.9
      - <<: *linux
        env: CONAN_GCC_VERSIONS=5
      - <<: *linux
        env: CONAN_GCC_VERSIONS=6
      - <<: *linux
        env: CONAN_GCC_VERSIONS=7
      - <<: *linux
        env: CONAN_GCC_VERSIONS=8
      - <<: *linux
        env: CONAN_GCC_VERSIONS=9
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=3.9
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=4.0
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=5.0
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=6.0
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=7.0 CONAN_DOCKER_IMAGE=conanio/clang7
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=8

install:
  - chmod +x .ci/install.sh
  - ./.ci/install.sh

script:
  - chmod +x .ci/run.sh
  - ./.ci/run.sh
