env:
   global:
     - CONAN_USE_DOCKER=1
     - CONAN_DOCKER_32_IMAGES=1
linux: &linux
   os: linux
   dist: xenial
   language: python
   python: "3.7"
   services:
     - docker
matrix:
   include:
      - <<: *linux
        env: CONAN_GCC_VERSIONS=4.9 CONAN_ARCHS=x86_64
      - <<: *linux
        env: CONAN_GCC_VERSIONS=4.9 CONAN_ARCHS=x86
      - <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_ARCHS=x86_64
      - <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_ARCHS=x86
      - <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_ARCHS=x86_64
      - <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_ARCHS=x86
      - <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_ARCHS=x86_64
      - <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_ARCHS=x86
      - <<: *linux
        env: CONAN_GCC_VERSIONS=8 CONAN_ARCHS=x86_64
      - <<: *linux
        env: CONAN_GCC_VERSIONS=8 CONAN_ARCHS=x86
      - <<: *linux
        env: CONAN_GCC_VERSIONS=9 CONAN_ARCHS=x86_64
      - <<: *linux
        env: CONAN_GCC_VERSIONS=9 CONAN_ARCHS=x86
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=3.9 CONAN_ARCHS=x86_64
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=3.9 CONAN_ARCHS=x86
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=4.0 CONAN_ARCHS=x86_64
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=4.0 CONAN_ARCHS=x86
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=5.0 CONAN_ARCHS=x86_64
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=5.0 CONAN_ARCHS=x86
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=6.0 CONAN_ARCHS=x86_64
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=6.0 CONAN_ARCHS=x86
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=7.0 CONAN_DOCKER_IMAGE=conanio/clang7 CONAN_ARCHS=x86_64
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=7.0 CONAN_DOCKER_IMAGE=conanio/clang7-x86 CONAN_ARCHS=x86
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=8 CONAN_ARCHS=x86_64
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=8 CONAN_ARCHS=x86

install:
  - chmod +x .ci/install.sh
  - ./.ci/install.sh

script:
  - chmod +x .ci/run.sh
  - ./.ci/run.sh
